steps:
  - name: golang:1.18.2
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -euxo pipefail
        apt-get update
        apt-get install -y jq
        make test
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -euxo pipefail
        docker build -t europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:${SHORT_SHA} .
        if [[ "${BRANCH_NAME}" == "master" ]]; then
          docker tag europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:${SHORT_SHA} europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:latest
          docker push europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:${SHORT_SHA}
          docker push europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:latest
        fi
options:
  logging: CLOUD_LOGGING_ONLY
