steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/badrobot:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euxo pipefail
        docker build -t gcr.io/$PROJECT_ID/badrobot:${SHORT_SHA} .
        if [[ "${BRANCH_NAME}" == "master" ]]; then
          docker push gcr.io/${PROJECT_ID}/badrobot:${SHORT_SHA}
        fi
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euxo pipefail
        if [[ "${BRANCH_NAME}" == "master" ]]; then
          gcloud beta run deploy badrobot \
            --image gcr.io/${PROJECT_ID}/badrobot:${SHORT_SHA} \
            --platform managed \
            --region us-central1
        fi

  # TODO(ajm): `make test-remote` on branch
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euxo pipefail
        JQ_VER="1.6"
        if [[ "${BRANCH_NAME}" == "master" ]]; then
          curl -Lo /usr/local/bin/jq "https://github.com/stedolan/jq/releases/download/jq-$${JQ_VER}/jq-linux64"
          chmod +x /usr/local/bin/jq
          make test-remote
        fi
